/**
 * @file nlst.h
 * @brief FTP NLST 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 NLST（Name List）命令的函数。
 * 该函数在主动模式（PORT）下，通过已建立的数据连接地址，
 * 向客户端返回指定目录中所有文件和子目录的名称列表（每行一个，以 \r\n 结尾）。
 *
 * 注意：
 *   - 仅支持主动模式（PORT），不支持被动模式（PASV）；
 *   - 列表内容仅为文件/目录名，不含属性、大小或时间（区别于 LIST 命令）；
 *   - 自动跳过 "." 和 ".." 条目；
 *   - 路径解析基于当前工作目录（ctx->cwd），支持相对路径；
 *   - 若未设置 PORT 命令，返回 425 错误；若路径无效，返回 550 错误。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：C 标准库 + 系统 Socket API（无第三方依赖）
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_NLST_HANDLER_H
#define FTP_NLST_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 客户端发送的 NLST 命令（简略文件列表）
 *
 * 本函数实现 FTP 的 NLST 命令，用于向客户端返回指定目录下所有文件和子目录的名称列表。
 * 数据通过主动模式（PORT）建立的数据连接发送。
 *
 * 功能流程：
 *   1. 检查是否已通过 PORT 命令设置数据连接地址（ctx->use_port_cmd == 1 表示已设置）；
 *   2. 解析可选路径参数，若无则使用当前工作目录（ctx->cwd）；
 *   3. 构建完整绝对路径；
 *   4. 连接到 ctx->client_data_ip:ctx->data_port；
 *   5. 打开目录并遍历所有条目；
 *   6. 将每个有效条目名称（非 "." / ".."）通过数据连接发送，格式为 "name\r\n"；
 *   7. 关闭数据连接；
 *   8. 在控制连接上依次返回 150（开始传输）和 226（传输完成）响应。
 *
 * 注意：
 *   - 不支持通配符、递归或符号链接解析；
 *   - 忽略 "." 和 ".." 条目；
 *   - 若路径无效、无法打开目录或不是目录，返回 550 错误；
 *   - 若未设置 PORT 或数据连接失败，返回 425 错误；
 *   - 所有网络 I/O 使用阻塞模式，适用于单线程 FTP 服务器模型。
 *
 * 成功时，函数最终向 `response` 写入：
 *     "226 Transfer complete.\r\n"
 * 若未设置 PORT，写入：
 *     "425 Use PORT or PASV first.\r\n"
 * 若路径无效，写入：
 *     "550 <path>: No such file or directory.\r\n"
 * 若数据连接失败，写入：
 *     "425 Cannot build data connection.\r\n"
 * 若发生内部错误（如缓冲区太小），返回 -1，此时 response 内容未定义。
 *
 * @param[in]  argument    指向 NLST 命令后的可选路径参数（可能为 NULL、空串或空白）。
 *                         若为 NULL 或仅含空白字符，则使用当前工作目录。
 * @param[out] response    用于填充最终控制连接响应消息的缓冲区（调用者必须保证非 NULL）。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 *                         建议至少 128 字节以容纳错误路径信息。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针，用于读取 cwd、client_data_ip 等字段。
 *                         必须已初始化，且包含以下关键字段（典型定义见 utils.h）：
 *                         - char cwd[1024];            // 当前工作目录（以 '/' 开头的绝对路径）
 *                         - char client_data_ip[16];   // 客户端数据连接 IP（如 "192.168.1.100"）
 *                         - uint16_t data_port;        // 客户端数据端口（网络字节序已转换为 host order）
 *                         - int use_port_cmd;          // 标记 PORT 是否已成功设置（1=已设，0=未设）
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效的 FTP 响应（无论操作成功或协议级错误）；
 *                         返回 -1 表示内部错误（如参数无效、内存问题、response 缓冲区不足等），
 *                         此时调用者不应依赖 response 的内容，应记录日志并关闭会话。
 *
 * @note
 *   - 本函数会尝试建立 TCP 连接到客户端指定的数据端口，请确保防火墙允许出站连接；
 *   - Windows 平台需在调用前初始化 Winsock（由主程序负责）；
 *   - 目录遍历行为在 Linux 和 Windows 上保持语义一致（仅返回基础名称）。
 */
int handle_ftp_nlst_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_NLST_HANDLER_H