/**
 * @file opts.h
 * @brief FTP OPTS 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 OPTS 命令（特别是 UTF8 选项）的函数。
 * 主要用于解析客户端发送的 "OPTS UTF8 ON" 等指令，并生成符合 RFC 2640 的标准响应。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_OPTS_HANDLER_H
#define FTP_OPTS_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 的 OPTS 命令，特别是 "UTF8 ON" 子命令。
 *
 * 本函数解析客户端发送的 OPTS 命令参数，若为 "UTF8 ON"（忽略大小写和前后空格），
 * 则返回标准成功响应 "200 UTF8 set to on."；否则返回不支持错误。
 *
 * @param[in]  argument   指向命令参数字符串的指针（如 "UTF8 ON"）。不可为 NULL。
 * @param[out] response   指向输出缓冲区的指针，用于存储服务器响应字符串。
 *                        调用者需确保该缓冲区足够大（建议至少 64 字节）。
 * @param[in]  resp_size  response 缓冲区的大小（以字节为单位），用于防止缓冲区溢出。
 *
 * @return int            返回 0 表示成功生成响应；返回 -1 表示参数无效或缓冲区太小。
 *
 * @note 本实现遵循 RFC 2640，对 UTF-8 支持返回 200 状态码。
 *       忽略参数中的前导/尾随空格，并进行不区分大小写的比较。
 *       目前仅支持 "UTF8 ON" 和 "UTF8 OFF"，其他参数（包括 MLST）均返回 504。
 */
int handle_ftp_opts_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_OPTS_HANDLER_H