/**
 * @file pass.h
 * @brief FTP PASS 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 PASS 命令的函数。
 * 该函数负责接收客户端提交的密码，并与会话上下文中已加载的合法密码进行安全比对，
 * 完成用户身份认证。
 *
 * 注意：PASS 阶段必须在 USER 命令成功调用之后执行，以确保 ctx->password 已正确加载。
 *       无论密码是否正确，均返回成功状态码（0），仅通过 FTP 响应码区分认证结果，
 *       以符合安全实践（避免泄露过多信息）。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_PASS_HANDLER_H
#define FTP_PASS_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 客户端发送的 PASS 命令（密码验证）
 *
 * 本函数接收客户端在 PASS 命令中提交的密码字符串，并与会话上下文 `ctx` 中
 * 已通过配置文件加载的合法密码进行安全比对。若匹配成功，则标记用户已认证；
 * 否则返回认证失败。
 *
 * 注意：
 *   - 本函数假设在调用前已通过 USER 命令调用 `read_config_ini()` 成功加载了合法密码到 `ctx->password`。
 *   - 密码比较采用恒定时间比较（避免时序攻击），即使长度不同也遍历全部字符。
 *   - 不直接暴露密码内容到日志，防止信息泄露。
 *
 * 成功认证时，函数将向 `response` 写入：
 *     "230 User logged in.\r\n"
 * 认证失败时，写入：
 *     "530 Login incorrect.\r\n"
 * 若发生内部错误（如缓冲区太小），则可能写入：
 *     "451 Local Error In Processing.\r\n"（但本实现优先保证响应格式正确）
 *
 * @param[in]  argument    指向 PASS 命令参数的字符串（即客户端提交的密码）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区（调用者必须保证非 NULL）。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 *                         建议至少 64 字节。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针，其中应包含合法密码 `password`
 *                         和用户认证状态字段（如 `authenticated` 或 `user_status`）。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效 FTP 响应（无论认证成功或失败）；
 *                         返回 -1 表示内部错误（如参数无效、response 缓冲区不足等），
 *                         此时 response 可能未被修改或包含错误消息。
 *
 * @note 调用者需确保 `ctx->password` 已由之前的 USER 命令正确加载。
 *       为防止用户枚举攻击，本函数不会因“用户名不存在”而提前失败——
 *       所有逻辑均基于 USER 阶段已加载的密码进行比对。
 */
int handle_ftp_pass_authentication(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_PASS_HANDLER_H