/**
 * @file port.h
 * @brief FTP PORT 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 PORT 命令的函数。
 * 该函数解析客户端在主动模式下通过 PORT 命令提交的数据连接地址和端口，
 * 格式为 "h1,h2,h3,h4,p1,p2"，并将其存储到会话上下文中供后续数据连接使用。
 *
 * 注意：
 *   - 仅支持 IPv4 地址格式，不支持 IPv6 或扩展语法。
 *   - 所有数值必须为 0～255 的十进制整数，且恰好 6 个字段。
 *   - 成功解析后，ctx 中将更新 client_data_ip、port_p1、port_p2 和 data_port 字段。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_PORT_HANDLER_H
#define FTP_PORT_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 客户端发送的 PORT 命令（主动模式数据连接地址通知）
 *
 * 本函数解析客户端发送的 PORT 命令参数，格式为 "h1,h2,h3,h4,p1,p2"，
 * 其中 h1～h4 为 IPv4 地址的四个十进制字节，p1 和 p2 为端口号的高/低字节。
 * 成功解析后，将客户端数据连接 IP、p1、p2 及完整端口号存入 ctx。
 *
 * 注意：
 *   - 严格校验参数数量（必须为6个非负整数，范围 0～255）
 *   - 不支持 IPv6 或其他扩展格式
 *   - 若解析失败，返回错误响应；成功则返回 200 响应
 *
 * 成功时，函数将向 `response` 写入：
 *     "200 PORT command successful.\r\n"
 * 解析失败时（如格式错误、数值越界、字段数量不对），写入：
 *     "501 Invalid PORT format.\r\n"
 * 若发生内部错误（如缓冲区太小或内存分配失败），可能返回 -1，
 * 此时 response 内容未定义或包含部分错误信息。
 *
 * @param[in]  argument    指向 PORT 命令参数的字符串（如 "192,168,1,100,10,200"）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区（调用者必须保证非 NULL）。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 *                         建议至少 64 字节。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针，用于存储解析结果。
 *                         必须已初始化，且包含足够空间的 client_data_ip 字段（建议 >=16 字节）。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效的 FTP 响应（无论参数是否合法）；
 *                         返回 -1 表示内部错误（如参数无效、内存分配失败、response 缓冲区不足等），
 *                         此时调用者不应依赖 response 的内容。
 *
 * @note 调用者需确保 `ctx` 结构体包含以下字段（典型定义见 utils.h）：
 *       - char client_data_ip[16];   // 存储 "a.b.c.d" 格式的字符串
 *       - unsigned char port_p1;     // 端口高字节
 *       - unsigned char port_p2;     // 端口低字节
 *       - uint16_t data_port;        // p1 * 256 + p2
 *       - int use_port_cmd;          // 标记 PORT 是否已设置
 */
int handle_ftp_port_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_PORT_HANDLER_H