/**
 * @file pwd.c
 * @brief FTP PWD 命令处理模块实现
 *
 * 本文件实现了用于处理 FTP 协议中 PWD 命令的函数。
 * PWD 命令用于获取当前工作目录（Print Working Directory）。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#include "../utils.h"
#include <string.h> // 用于 strlen 和 strrchr

/**
 * @brief 处理 FTP 客户端发送的 PWD 命令
 *
 * 本函数响应客户端发送的 PWD 命令，返回当前工作目录信息。
 * 根据 FTP 协议标准（RFC 959），返回格式为 "257 <directory path>"。
 *
 * PWD 命令通常在登录后使用，用于获取服务器上的当前工作目录路径。
 * 此命令不需要认证，任何用户都可以执行。
 *
 * @param[in]  argument    指向 PWD 命令参数的字符串（通常为空，无需参数）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区（调用者必须保证非 NULL）。
 *                         建议至少 64 字节。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针。
 *                         此函数使用 ctx->cwd 来获取当前工作目录。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效响应；
 *                         返回 -1 表示参数无效或缓冲区太小。
 */
int handle_ftp_pwd_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx)
{
    // 参数校验：确保输入参数有效
    if (argument == NULL || response == NULL || resp_size == 0 || ctx == NULL) {
        return -1; // 无效参数
    }

    // 从上下文中获取当前工作目录
    const char* cwd = ctx->cwd;
    
    // 如果当前工作目录为空，则使用根目录
    if (cwd == NULL || strlen(cwd) == 0) {
        cwd = "/";
    }

    // 计算响应所需的空间："257 \"" + 路径 + "\"\r\n" + 终止空字符
    size_t cwd_len = strlen(cwd);
    size_t response_len = 5 + 2 + cwd_len + 3 + 1; // "257 \"" + cwd + "\"\r\n" + \0

    // 检查缓冲区是否足够
    if (resp_size < response_len) {
        LOG_ERROR("Response buffer too small for PWD message.");
        return -1; // 缓冲区不足
    }

    // 构建响应消息：257 "/path"
    // 使用 snprintf 确保安全写入
    int written = snprintf(response, resp_size, "257 \"%s\"\r\n", cwd);
    
    if (written < 0 || (size_t)written >= resp_size) {
        LOG_ERROR("Failed to write PWD response.");
        return -1;
    }

    LOG_DEBUG("PWD command processed, current directory: %s", cwd);

    return 0; // 成功
}
