/**
 * @file syst.h
 * @brief FTP SYST 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 SYST 命令的函数。
 * SYST 命令用于获取服务器操作系统类型信息。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_SYST_HANDLER_H
#define FTP_SYST_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 客户端发送的 SYST 命令
 *
 * 本函数响应客户端发送的 SYST 命令，返回服务器操作系统类型信息。
 * 根据 FTP 协议标准（RFC 959），返回格式为 "215 UNIX Type: L8"，
 * 表示服务器为 UNIX 系统，使用 8 位字节的二进制传输模式。
 *
 * SYST 命令通常在登录后使用，用于客户端确定服务器的文件系统特性。
 * 此命令不需要认证，任何用户都可以执行。
 *
 * 成功时，函数将向 `response` 写入标准 FTP 响应：
 *     "215 UNIX Type: L8\r\n"
 *
 * @param[in]  argument    指向 SYST 命令参数的字符串（通常为空，无需参数）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区（调用者必须保证非 NULL）。
 *                         建议至少 64 字节。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针。
 *                         此函数不使用 ctx，仅保留函数签名一致性。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效响应；
 *                         返回 -1 表示参数无效或缓冲区太小。
 *
 * @note 根据 RFC 959，标准的系统类型响应格式为：
 *       215 <system name> [<additional info>]
 *       常用响应包括：
 *       - "215 UNIX Type: L8"
 *       - "215 Windows_NT"
 *       - "215 VMS"
 */
int handle_ftp_syst_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_SYST_HANDLER_H