/**
 * @file syst.c
 * @brief FTP SYST 命令处理模块实现
 *
 * 本文件实现了用于处理 FTP 协议中 SYST 命令的函数。
 * SYST 命令用于获取服务器操作系统类型信息。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#include "../utils.h"
#include <string.h> // 用于 strlen

// 获取系统类型字符串的宏定义
#if defined(_WIN32) || defined(_WIN64)
#define FTP_SYSTEM_TYPE "215 Windows_NT\r\n"
#define FTP_SYSTEM_NAME "Windows"
#elif defined(__linux__)
#define FTP_SYSTEM_TYPE "215 UNIX Type: L8\r\n"
#define FTP_SYSTEM_NAME "Linux"
#elif defined(__APPLE__) && defined(__MACH__)
#define FTP_SYSTEM_TYPE "215 UNIX Type: L8\r\n"
#define FTP_SYSTEM_NAME "macOS"
#elif defined(__unix__)
#define FTP_SYSTEM_TYPE "215 UNIX Type: L8\r\n"
#define FTP_SYSTEM_NAME "Unix"
#else
#define FTP_SYSTEM_TYPE "215 UNIX Type: L8\r\n"
#define FTP_SYSTEM_NAME "Unknown"
#endif

/**
 * @brief 处理 FTP 客户端发送的 SYST 命令
 *
 * 本函数响应客户端发送的 SYST 命令，返回服务器操作系统类型信息。
 * 根据 FTP 协议标准（RFC 959），返回格式为 "215 <system name> [<additional info>]"。
 *
 * 函数会根据编译和运行时的系统环境自动返回对应的系统类型：
 *   - Windows: "215 Windows_NT"
 *   - Linux: "215 UNIX Type: L8"
 *   - macOS: "215 UNIX Type: L8"
 *   - 其他 Unix: "215 UNIX Type: L8"
 *
 * "UNIX Type: L8" 表示：
 *   - UNIX 操作系统
 *   - L8 表示使用 8 位字节的二进制传输模式（Stream mode）
 *
 * SYST 命令通常在登录后使用，用于客户端确定服务器的文件系统特性。
 * 此命令不需要认证，任何用户都可以执行。
 *
 * @param[in]  argument    指向 SYST 命令参数的字符串（通常为空）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区。
 *                         建议至少 64 字节。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针。
 *                         此函数不使用 ctx，仅保留函数签名一致性。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效响应；
 *                         返回 -1 表示参数无效或缓冲区太小。
 */
int handle_ftp_syst_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx)
{
    // 参数校验：确保输入参数有效
    if (argument == NULL || response == NULL || resp_size == 0 || ctx == NULL) {
        return -1; // 无效参数
    }

    // 获取系统类型字符串的长度
    size_t sys_type_len = strlen(FTP_SYSTEM_TYPE);

    // 检查缓冲区是否足够（需要额外的空间用于终止空字符）
    if (resp_size <= sys_type_len) {
        LOG_ERROR("Response buffer too small for system type message.");
        return -1; // 缓冲区不足
    }

    // 根据系统类型填充响应
    // 使用 memcpy 避免 snprintf 的格式化开销，同时确保安全
    memcpy(response, FTP_SYSTEM_TYPE, sys_type_len);
    response[sys_type_len] = '\0';

    LOG_DEBUG("SYST command processed, system type: %s", FTP_SYSTEM_NAME);

    return 0; // 成功
}
