/**
 * @file user。h
 * @brief FTP USER 命令处理模块头文件
 *
 * 本文件声明了用于处理 FTP 协议中 USER 命令的函数。
 * 该函数负责接收客户端提交的用户名，
 * 并从 config.ini 配置文件中加载该用户信息与密码，为后续 PASS 认证做准备。
 *
 * 注意：USER 阶段不进行身份验证，仅记录信息并加载配置。
 *       实际认证在 PASS 命令处理时完成，以防止用户枚举攻击。
 *
 * 支持平台：Linux、Windows（通过 MinGW 或 GCC 编译）
 * 依赖：仅使用 C 标准库，无第三方依赖。
 *
 * @author Generated by Qwen
 * @date 2026-01-19
 */

#ifndef FTP_USER_HANDLER_H
#define FTP_USER_HANDLER_H

#include <stddef.h> // 用于 size_t
#include "../utils.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 处理 FTP 客户端发送的 USER 命令
 *
 * 本函数解析客户端在 USER 命令中提供的用户名，并将其暂存于会话上下文 `ctx` 中。
 * 同时，从配置文件 config.ini 中加载合法的用户名与对应密码，也存入 `ctx`，
 * 为后续的 PASS 命令认证做准备。
 *
 * 注意：此阶段不进行用户名合法性校验，仅完成参数记录与配置加载。
 *       实际的身份验证将在接收到 PASS 命令后执行。
 *
 * 成功时，函数将向 `response` 写入标准 FTP 响应：
 *     "331 User name okay, need password.\r\n"
 * 若发生内部错误（如配置文件缺失），则写入：
 *     "451 Local Error In Processing.\r\n"
 *
 * @param[in]  argument    指向 USER 命令参数的字符串（即客户端提交的用户名）。
 *                         不可为 NULL。
 * @param[out] response    用于填充响应消息的缓冲区（调用者必须保证非 NULL）。
 * @param[in]  resp_size   response 缓冲区的大小（字节数），用于防止缓冲区溢出。
 *                         建议至少 64 字节。
 * @param[in,out] ctx      指向当前客户端会话上下文的指针，用于保存用户名及配置信息。
 *                         不可为 NULL。
 *
 * @return int             返回 0 表示成功处理并已填充有效响应；
 *                         返回 -1 表示内部错误（如配置读取失败、参数无效等），
 *                         此时 response 可能已被填充为错误消息。
 *
 * @note 无论客户端提供的用户名是否存在于 config.ini，
 *       本函数均返回成功（即始终允许进入 PASS 阶段），
 *       以符合 FTP 安全最佳实践（防止用户枚举）。
 */
int handle_ftp_user_command(const char* argument, char* response, size_t resp_size, client_context_t* ctx);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // FTP_USER_HANDLER_H